### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by DJNing** [utiasASRL/hero_radar_odometry#23]
Hello, can you elaborate a bit on the sturcture of the data root directory?

**Comment by keenan-burnett** [comment]
I'm assuming you're trying to use the oxford radar dataset?
On my setup, the root folder is the path to where all the oxford sequences are stored, so:
`/raid/krb/oxford-radar-robotcar-dataset/`

Within this folder, you have 32 different sequences, for example:
```
2019-01-10-11-46-21-radar-oxford-10k
2019-01-10-12-32-52-radar-oxford-10k
2019-01-10-14-02-34-radar-oxford-10k
...
```

Within each of the sequences, if you download them properly, you will have:
```
gt/
radar/
radar.timestamps
```

Have a look at their [repo](https://github.com/oxford-robotics-institute/radar-robotcar-dataset-sdk) for instructions on how to download their dataset.

**Comment by DJNing** [comment]
Thank you very much for your quick reply! This is very helpful
